### ISSUE TITLE
Manifest Spec: Restrict to Context

### ISSUE THREAD

**Issue by rawkode** [comtrya/comtrya#14]
Only run a manifest if it meets the criterion, which can match the context tree.

**Comment by vielmetti** [comment]
I could use this, I think - trying to do a single set of config files that do the right thing across multiple versions of Ubuntu, and if there was a conditional I could set that reflected the version number or string I could express the condition e.g. "only install the deadsnakes PPA on 20.04"

**Comment by rawkode** [comment]
Closed by #122

**Comment by svallory** [comment]
> I could use this, I think - trying to do a single set of config files that do the right thing across multiple versions of Ubuntu, and if there was a conditional I could set that reflected the version number or string I could express the condition e.g. "only install the deadsnakes PPA on 20.04"

I know it's been more than a year, but just in case, for anyone looking, you can achieve that with [variant conditions](https://www.comtrya.dev/core/manifests/variants). The `where` attribute takes a koto statement or block as long as it returns a boolean.

**Comment by airtonix** [comment]
https://github.com/koto-lang/koto/blob/main/docs/language/basics.md

**Comment by airtonix** [comment]
Actually I think @rawkode replaced koto with Rhai

#180

**Comment by airtonix** [comment]
https://rhai.rs/book/engine/builtin.html

**Comment by rawkode** [comment]
Yeah, we did replace Koto with Rhai because we could restrict Rhai to expression only mode.

Hopefully this works well for people :)

**Comment by svallory** [comment]
> Yeah, we did replace Koto with Rhai because we could restrict Rhai to expression only mode.

I was relying on the ability to pass a block to import koto functions and do some perform decisions :/

**Comment by svallory** [comment]
I don't know if changing it again is on the menu, but have you considered Rhai's limitations? https://rhai.rs/book/about/non-design.html

I was already missing not having access to the file system from Koto. Have you considered using Lua? https://www.lua.org/

**Comment by svallory** [comment]
Also, a crazy thought... what if we had a DSL for specifying manifests? If you dig that idea, I can help by specifying the language we define in Xtext. A DSL could have instructions for embedding code in any language. With an xtext definition it is also possible to generate vscode extensions for syntax highlight, autocomplete etc

**Comment by rawkode** [comment]
> I was relying on the ability to pass a block to import koto functions and do some perform decisions :/

Can you share some example use-cases?

Lua is definitely something I'd consider, as long as there's enough potential to make it worth another change.

> Also, a crazy thought... what if we had a DSL for specifying manifests? If you dig that idea, I can help by specifying the language we define in Xtext. A DSL could have instructions for embedding code in any language. With an xtext definition it is also possible to generate vscode extensions for syntax highlight, autocomplete etc

I'd be happy to discuss and help support a DSL. We've discussed supporting other formats beyond YAML, so this would fit nicely into that discussion.

**Comment by svallory** [comment]
> Can you share some example use-cases?

The first thing I used koto blocks for was to call a custom `get_distribution` function I had on and a `utils.koto` file. I don't remember why I had to do that but I was using Zorin at the time. I was planning on expanding on contexts by having the block determine the context (e.g. work, personal, remote, etc). I didn't stop to figure out how I would do that exactly without fs access. That's why I mentioned I missed that ability from koto

But think about it... comtrya is used by programmers. Programmers who are taking the time to set up their homes exactly as they want in a reproducible way. That's the most nit-picking public you'll find. For me it makes sense to allow them the flexibility to run whatever they want to control comtrya and blocks in `where` is a very cheap way to let them control the flow.

I imagine that if comtrya becomes really popular, as I think it will someday, we'll start getting a lot of requests to add stuff to contexts just so it can be used in `where`s.

About the DSL, how about you start a discussion on that? Looks like you already have some thoughts to share
