### ISSUE TITLE
Support MacPorts as macOS provider

### ISSUE THREAD

**Issue by theowenyoung** [comtrya/comtrya#191]
MacPorts is also a popular package manager in macOS: <https://guide.macports.org>,

Consider MacPorts as a provider?

**Comment by rawkode** [comment]
Yep! We can add this

**Comment by martintc** [comment]
Working on the basic support for installing a package. Would like to also include boot strap capabilities. 

Do we think it would be okay to just build from source or do we want to specifically get a version like `MacPorts-2.7.2-12-Monterey`

**Comment by martintc** [comment]
Reopen as I would like to keep this open until the bootstrap procedure is done

**Comment by icepuma** [comment]
I think the bootstrap can't be automated, unless we pin a set of prerequirements:
- Xcode installed
- Xcode license accepted

What about installing `pkg` - files via terminal? Is `/usr/sbin/installer` still the way? Because it requires the user to specify a location, which shouldn't be chosen by `comtrya` I guess.

**Comment by martintc** [comment]
> I think the bootstrap can't be automated, unless we pin a set of prerequirements:
> 
>     * Xcode installed
> 
>     * Xcode license accepted
> 
> 
> What about installing `pkg` - files via terminal? Is `/usr/sbin/installer` still the way? Because it requires the user to specify a location, which shouldn't be chosen by `comtrya` I guess.

Ill see if I can get around it, but yea, it looks like it is going to either not be possible or require some inventiveness. Ill go ahead and close the issue.
