### ISSUE TITLE
Major Docs Overhaul

### ISSUE THREAD

**Issue by rawkode** [comtrya/comtrya#303]
**Description**

We've (I) have done a seriously poor job at maintaining and keeping the docs up to date.

I believe this is, in-part, because the docs are in a separate repository and as such are often neglected.

I'm proposing that we bring the docs into the main repo, which will work with now that we're a multi-crate project anyway.

This would likely mean that we move away from Gitbook, as I'm not sure if we could support that structure (maybe?).

However, there was chat about moving to mdBook or something also on a contributor call.

Opening for discussion.

cc @comtrya/maintainers

**Comment by icepuma** [comment]
https://github.com/comtrya/comtrya/issues/261

**Comment by rawkode** [comment]
I think they're related but we should keep both open until we have some decisions

**Comment by martintc** [comment]
I like the idea of bringing it into the repo. It would be easier, if we wanted to, stipulate that a PR for new features doesn't just include the implementation, but documentation. Which I have my own hand in this blame game since I don't think users and groups are properly documented. 

I personally am a fan of mdbook since writing the docs would just be in plain markdown.

**Comment by icepuma** [comment]
I really like the idea about `rustdoc`, because it lives next to the code. But the doc we want to have for the end user is not the doc, `rustdoc` aims for. I'm with @martintc on the `mdbook` train

**Comment by icepuma** [comment]
I already initialized a `mdbook` project inside https://github.com/comtrya/comtrya/tree/main/docs

**Comment by airtonix** [comment]
up to date docs would be amazeballs.

**Comment by martintc** [comment]
Closing because we now have mdbook
