### ISSUE TITLE
[ feature request ]: Use rustls instead of openssl

### ISSUE THREAD

**Issue by yonas** [comtrya/comtrya#409]
rustls offers better portability and ease of compiling.

**Comment by martintc** [comment]
We've been trying, but its been an issue of not our direct dependencies but our transitive dependencies. Crates we rely on that have not either converted over to using rustls or will not. Or some that have technical issues or they are waiting on transitive dependencies. An example is, for git we Rawkode's gitsync which uses git2, which doesn't (although it been awhile since I've checked) use rustls. For this case, we are waiting for gitoxide to offer what we need, but the last time I looked this past October, gitoxide was still a ways away in offering features we needed.

**Comment by shawn111** [comment]
@martintc Is it a good idea to make git related function as feature? Let the main part of comtrya can remove the dependencies of openssl

**Comment by martintc** [comment]
That is one possibility. I can talk with the other maintainers about that. Another solution @rawkode has thrown out there is to scrub git sync and have comtrya pull a pre-compiled git binary and use that instead of a library that replicates the functions of git.

**Comment by yonas** [comment]
> ... have comtrya pull a pre-compiled git binary and use that instead of a library that replicates the functions of git.

I'm not a fan of having to pull dependencies off the Internet at runtime. Maybe you meant at compile-time. Even so, once `git sync` is removed, `gitoxide` can take care of everything `comtrya` needs.

**Comment by rawkode** [comment]
Should we just remove Git support? This has plagued us for such a long time and people can always git clone before running Comtrya. 

This would also drastically reduce the binary size.

**Comment by martintc** [comment]
Yea, I think at this point, we just remove git. Ill create an issue to remove that. Ill probably also assign it to myself.
