### ISSUE TITLE
Bug: apply from online repository panics

### ISSUE THREAD

**Issue by thebino** [comtrya/comtrya#511]
**Description**
When I try to apply my manifests from repository, it fails.

**Example manifest**
```
comtrya -d https://github.com/thebino/dotfiles apply -m apps.gnupg
ERROR execute: Failed to find manifests at https://github.com/thebino/dotfiles
thread 'main' panicked at lib/src/manifests/mod.rs:57:13:
explicit panic
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Steps to reproduce**
Step by step explanation. Please add the output of with `-vvv` flag enabled (be careful not to include any secrets from your config).

**Expected behaviour**
What the expected behaviour in your opinion.

**Environment**
- OS: macOS Sequoia
- Version: 0.9.0

**Additional information**
Add more context which didn't fit in the fields above.

**Comment by martintc** [comment]
Since I pushed new releases rather fast with v0.8.9 and v0.9.0, which is why it probably why you didnt catch it until v0.9.0, but we axed the git integration with comtrya in #439 due to all of the issues it presents with libssl. The thought is, eventually we will bring it back when a suitable replacement like gitoxide is ready, or some other alternative.

**Comment by thebino** [comment]
Okay got it, would love to see it coming back soon.
Its makes it a breathe to share configurations between devices and installations

**Comment by martintc** [comment]
Yea, it does. Over the next few days I am going to play around with gix and gitoxide and see if it finally has what we need. Last time I checked was about 6 months ago, so lets hope.

**Comment by martintc** [comment]
Sorry I've been quiet on this. I think I have a path. I've got a little test project that does some interaction with the gix library. It is gonna pull in quite a few transitive dependencies, but I am also gonna try to whittle it down using feature flags. With some little bit of cutting with feature flags, I believe it required about 180 dependencies. I think I can get that lower.

To make the code a little cleaner in comtrya, I may wrap gix in a separate repo so and pull it in as a dependency sort of like how @rawkode did the initial git integration with his git-sync library. I may also take another stab at using git-sync, but having it use six with a feature flag. This was a path I was going down last year.

**Comment by thebino** [comment]
I'm really not in a hurry here, I understand that this requires a deep investigation and lots of tests to make it right this time. I haven' red the issues you mentioned yet but maybe I'll find time in the wintermonths. Thanks a lot for your contribution 🎉

**Comment by martintc** [comment]
@thebino if your able to, I have the beginnings of the solution. This doesn't quiet yet solve using git as a source for manifests, but its a start with first implementing a `git.clone` action based on using gix in lieu of git2rs/git-sync/openssl. If you're able to build that branch and run a couple test manifests with a `git.clone` action, it would be much appreciated. If this works well for people, then rebuilding using git as a manifest source should be trivial since this is the heart of that.

**Comment by martintc** [comment]
If you do, just be advise that I have changed the action slightly. An example manifest is in that branch.

**Comment by thebino** [comment]
I just tested it and it went smooth: https://github.com/thebino/dotfiles/commit/a574dbead7dcbb719e9b076ccfe941c6a8567be9

Will look forward to check the whole manifest repo from url again 🎉

**Comment by martintc** [comment]
I think that PR is a good start to getting souring git repos with fix. If you wouldn't mind sanity checking it for me before I pull it in.

**Comment by thebino** [comment]
Tested successfully on a M4 Mac. And I'm building it on a Raspberry Pi 1 right now 😂

**Comment by martintc** [comment]
> Tested successfully on a M4 Mac. And I'm building it on a Raspberry Pi 1 right now 😂

Sweet! I really appreciate you testing this out and validating the functionality for me!

**Comment by martintc** [comment]
I am going to go-ahead and close this issue. If there is anything missing, let me know with a new issue. Thank you!
