### ISSUE TITLE
Need a way to restrict package providers to supported platforms

### ISSUE THREAD

**Issue by rawkode** [comtrya/comtrya#66]

**Comment by bketelsen** [comment]
and/or specify a default package provider if one is supported on multiple platforms (I don't want to use homebrew even if it is available on Linux)

**Comment by kraileth** [comment]
This might be somewhat more complex than it seems at first. It may be somewhat exotic, but there are projects like e.g. _openpkg.org_ that provide packages for various platforms (Linux, *BSD, Solaris, macOS, ...). They use (self-provided) RPM on all of those and a rpm/yum provider would probably just work with it even on distributions / systems that are not Redhat / SuSE / Mageia / etc. _Ravenports_ (a project that I am contributing to) is also providing cross-platform packages but we're using a package manager that is basically compatible with pkg(8). So the bsdpkg provider could in fact also be useful on Linux and Solaris / illumos if somebody uses Ravenports.

But even those very special cases aside - dpkg and rpm for example are available as pkg(8) packages on FreeBSD. If someone were to publish a repo with e.g. DEB packages geared towards FreeBSD, Debian's package manager could be used for package management. A now defunct fork that started as "Arch BSD" and was later renamed to "PacBSD" was basically FreeBSD but used Arch Linux' Pacman package manager.

It might make sense to just define defaults for known operating systems / distributions but let users with special needs use "provider: $SOMETHING" to override the default provider on a per-action basis. @bketelsen's suggestion would also be very helpful. What about the following:

1) No provider is defined by the user in either the configuration nor in the manifest. Comtrya uses what it thinks is the system default (for known operating systems / distributions).
2) The user has defined a default provider. Whenever there's no explicit provider definition in a package.XYZ action that provider would be used instead of what Comtrya would do on that OS / distro otherwise.
3) If a provider is defined for a certain action, that definition takes precedence over the other two sources.

**Comment by martintc** [comment]
At least on the linux side. I have been working with someone to create a sort of extension to the os_info details that will allow for better detailing of a linux system that Comtrya may be able to leverage. It will try to construct details on linux distros at run time. One advantage is that we are working on returning information such as a list of available package managers since while it is becoming a bit for popular. For instance, Ubuntu shipping with both apt and snap. Fedora with dnf and flatpaks. Or even people running distributions like Slackware that are utilizing the Nix package manager.

**Comment by martintc** [comment]
I think I am going to close this. Thinking about the details more, we sort of solve this with specifying a provider. Its not a bad solution, and I agree not the best. I have an idea, but I am still thinking on it. Will open an issue with my solutions so I have a little better track. 

Essentially, can we specify the default package manager in the variables and contexts and utilize that. Multiple systems do support multiple package managers. I am thinking, if we can override the default and just do it in one location. Then specifying a provider in an action would only be necessary in certain scenarios.
